#!/bin/bash
# Kaoz basic client
# Usage: echo "mesage" |ircpipe [#channel]

# Change these settings to match the configuration of the server
LISTENER_PASSWORD='MyVerySecretPassword'
LISTENER_HOST='Kaoz-server-hostname'
LISTENER_PORT=9010

# Default channel
DEFAULT_CHANNEL='#default-channel'

# Send the real message
if [ $# -ne 1 ]
then
    CHANNEL="$CHANNEL"
else
    CHANNEL="$1"
fi

FILENAME="`mktemp --suffix .ircpipe`"
while read LINE
do
echo "${LISTENER_PASSWORD}:${CHANNEL}:(`hostname`) $LINE" >> $FILENAME
done
socat - OPENSSL:${LISTENER_HOST}:${LISTENER_PORT},crnl,verify,cafile=/etc/ssl/kaoz/server.pem < $FILENAME
rm $FILENAME

