#!/bin/bash
# Send Nagios notifications to Kaoz with ircpipe and irc colors
# Usage example:
#  nagios-ircpipe #mynagioschan CRIT PROBLEM "service name" "Something weird happened"
# will send to "ircpipe #mynagioschan" this message:
#  [Nagios] CRIT (PROBLEM) serice name: Something weird happened

# Configure the directory where ircpipe is
KAOZ_IRCPIPE_PATH='/usr/share/kaoz-client'
source "$KAOZ_IRCPIPE_PATH/stdirc"

case "$2" in
  OK | UP)
    color="3";
    status=" OK ";
    ;;
  WARNING | UNREACHABLE)
    color="8";
    status="WARN";
    ;;
  CRITICAL | DOWN)
    color="4";
    status="CRIT";
    ;;
  *)
    color="11";
    status=" ?? ";
    ;;
esac

/usr/bin/printf "${K}6[%s] ${K}%s%s %s\n" "Nagios" "$color" "$status ($3)" "$4: $5" | "$KAOZ_IRCPIPE_PATH/ircpipe" $1

