language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

env:
  - IRC_VERSION=11.1
  - IRC_VERSION=12.1
  - IRC_VERSION=12.1.1
  # Test the latest revision too
  - IRC_VERSION=

install:
  - if [ -n "$IRC_VERSION" ] ; then pip install irc==$IRC_VERSION ; else pip install irc ; fi

script: "python setup.py test"

sudo: false

notifications:
  email: false
  irc: "irc.rezosup.org#kaoz"
