#!/bin/bash
# Kaoz basic client
# Usage: echo "mesage" |ircpipe [#channel]

# Change these settings to match the configuration of the server
LISTENER_PASSWORD='MyVerySecretPassword'
LISTENER_HOST='Kaoz-server-hostname'
LISTENER_PORT=9010
LISTENER_SSL=true
LISTENER_CRT='/etc/ssl/kaoz/server.crt' #This file should only contain the certificate, not the key ;-)

# Default channel
DEFAULT_CHANNEL='#default-channel'

# Send the real message
if [ $# -ne 1 ]
then
    CHANNEL="$DEFAULT_CHANNEL"
else
    CHANNEL="$1"
fi

FILENAME="`mktemp --suffix .ircpipe`"
while read LINE
do
echo "${LISTENER_PASSWORD}:${CHANNEL}:(`hostname`) $LINE" >> $FILENAME
done
if $LISTENER_SSL ; then
    socat - OPENSSL:${LISTENER_HOST}:${LISTENER_PORT},crnl,verify,cafile=${LISTENER_CRT} < $FILENAME
else
    socat - TCP:${LISTENER_HOST}:${LISTENER_PORT} < $FILENAME
fi
rm $FILENAME

