#!/bin/sh
# Send NUT UPS alerts to Kaoz with ircpipe and irc colors
#
# Usage: upsalert <upsname> <notifytype>
#
# Known values for <notifytype> are:
# ONBATT, ONLINE, LOWBATT, REPLBATT, COMMBAD, COMMOK, FSD, SHUTDOWN, NOPARENT

# Configure the directory where ircpipe is
KAOZ_IRCPIPE_PATH='/usr/share/kaoz-client'
source "$KAOZ_IRCPIPE_PATH/stdirc"

OK=" ${K}3OK "
WARN="${K}8WARN"
CRIT="${K}4CRIT"
UNKNOWN=" ${K}11?? "

level=$UNKNOWN
message="Received $2 from $1"

case $2 in
    on-battery)
        level=$WARN
        message="$1: sur batterie"
        ;;
    on-line)
        level=$OK
        message="$1: branché sur secteur"
        ;;
    low-battery)
        level=$CRIT
        message="$1: batterie faible"
        ;;
    replace-battery)
        level=$CRIT
        message="$1: batterie à remplacer"
        ;;
    commbad)
        level=$WARN
        message="$1: communication coupée"
        ;;
    commok)
        level=$OK
        message="$1: communication rétablie"
        ;;
    fsd)
        level=$CRIT
        message="Shutdown forcé en cours"
        ;;
    shutdown)
        level=$CRIT
        message="Shutdown en cours"
        ;;
    noparent)
        message="Processus orphelin"
        ;;
esac

echo -e "${K}6[upsmon]${O} $level $message" | "$KAOZ_IRCPIPE_PATH/ircpipe"

