#!/bin/sh
# This script is executed each time someone logs in

KAOZ_IRCPIPE_PATH='/usr/share/kaoz-client'
source "$KAOZ_IRCPIPE_PATH/stdirc"

if [ $PAM_TYPE = "open_session" ];
then
    if [ $PAM_SERVICE = "login" ];
    then
        # Local login
        message="${K}11local login$O -- ${B}${K}7${PAM_USER}$O ${K}3logged on$O $PAM_TTY"
    elif [ $PAM_SERVICE = "sshd" ];
    then
        # SSH login
        message="${K}6ssh $O -- ${B}${K}7${PAM_USER}$O ${K}3logged on $O from $PAM_RHOST"
    else
        message="${K}4Abnormality -- $PAM_USER logged on $PAM_TTY from $PAM_RHOST using $PAM_SERVICE and $PAM_RUSER"
    fi
elif [ $PAM_TYPE = "close_session" ];
then
    if [ $PAM_SERVICE = "login" ];
    then
        # Local logout
        message="${K}11local login$O -- ${B}${K}7${PAM_USER}$O ${K}5logged off$O $PAM_TTY"
    elif [ $PAM_SERVICE = "sshd" ];
    then
        # SSH logout
        message="${K}6ssh $O -- ${B}${K}7${PAM_USER}$O ${K}5logged off$O from $PAM_RHOST"
    else
        message="${K}4Abnormality -- $PAM_USER logged off $PAM_TTY from $PAM_RHOST using $PAM_SERVICE and $PAM_RUSER"
    fi
else
    message="${K}4Abnormality -- Unhandled call to the logger. Data=$PAM_RHOST, $PAM_RUSER, $PAM_SERVICE, $PAM_TTY, $PAM_USER and $PAM_TYPE"
fi
echo -e $message | "$KAOZ_IRCPIPE_PATH/ircpipe"

